airlines = { SOI ~ NL? ~ (COMMENT | definition)+ ~ EOI }

definition = {
    designator ~ "\t" ~ airline ~ "\t" ~ callsign ~ "\t" ~ country ~ NL
}

// tab_delimited_text       = @{ (!(NL | (" "* ~ "\t")) ~ ANY)* }

designator = @{ ASCII_ALPHA_UPPER{3} }
airline    = @{ tab_delimited_text }
callsign   = @{ tab_delimited_text }
country    = @{ tab_delimited_text }

COMMENT    = _{ (";" | "//") ~ (!NEWLINE ~ ANY)* }
WHITESPACE = _{ " " }
