symbology = { SOI ~ NL? ~ header ~ items ~ symbols ~ EOI}

header = { "SYMBOLOGY" ~ NL ~ "SYMBOLSIZE" ~ NL }

items = _{ item+ }
item = { name ~ ":" ~ name ~ ":" ~ number ~ ":" ~ DECIMAL ~ ":" ~ number ~ ":" ~ number ~ ":" ~ number ~ NL }

symbols = { "SYMBOL" ~ ANY+ }

name = @{ (!":" ~ ANY)+ }
number = @{ "-"? ~ ASCII_DIGIT+ }
DECIMAL = @{ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ }

NL = _{ NEWLINE+ }
